### PR TITLE
ENHANCEMENT: Add Dockerfile and push builds to Github Container Registry

### PR DESCRIPTION
**Pull request by kieraneglin**
Partially based off this PR: https://github.com/ligh7s/smoked-salmon/pull/1

## What does it do?

- Adds a Dockerfile so the project can more easily and reliably be set up AND it can more easily be selfhosted
- Adds a build step that pushes the latest container to Github Container Registry (GHCR)
  - This adds a new build with a tag of `latest` and the current date each time code is pushed to `master`
  - NOTE: this likely requires that the `elghoto-version` branch be pushed to `master`
  - GHCR is free for open source repos. You will not be charged for its use

### CODE REVIEW

**Comment by ghoto** [comment]
Hey. Thanks, I'll review this today or tomorrow

**Review by ghoto — APPROVED** [review]
LGTM

**Comment by AN1MATEK** [comment]
Thanks guys! Great work!

Just to be sure, is this what I should be pulling? `ghcr.io/ghoto/smoked-salmon:elghoto-version`

🍻

**Comment by backstab5983** [comment]
> Thanks guys! Great work!
> 
> Just to be sure, is this what I should be pulling? `ghcr.io/ghoto/smoked-salmon:elghoto-version`
> 
> 🍻

I don't see any package published yet. I suppose as the PR mentions the `elghoto-version` branch needs to pushed to `master`

**Comment by ghoto** [comment]
Done folks. It should be here.

`ghcr.io/ghoto/smoked-salmon:latest`

**Pull request merged**
